"""Gayatri AI — Age- and Grade-Appropriate Safety & Integrity Policy Engine.

Evaluates user inputs and model outputs against safety boundaries,
developmental age appropriateness, and academic integrity guardrails.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from enum import Enum

logger = logging.getLogger("gayatri.safety")


class GradeBand(str, Enum):
    """Educational developmental stages for safety policies."""
    ELEMENTARY = "elementary"  # Grades K-5
    MIDDLE = "middle"          # Grades 6-8
    HIGH = "high"              # Grades 9-12
    ADULT = "adult"            # Higher education / adult learner


@dataclass
class SafetyDecision:
    """Result of a safety evaluation."""
    allowed: bool
    reason: str = ""
    is_cheating_attempt: bool = False
    socratic_redirection: str = ""


class SafetyPolicyEngine:
    """Evaluates student and tutor dialogues against safety and academic honesty policies."""

    # Academic dishonesty detection patterns
    CHEATING_PATTERNS = [
        re.compile(r"\b(solve|answer)\s+(my|this)\s+(exam|test|quiz)\b", re.IGNORECASE),
        re.compile(r"\b(write|do)\s+(my\s+whole|all\s+my|my\s+entire)\s+(homework|assignment|essay)\b", re.IGNORECASE),
        re.compile(r"\b(give\s+me|tell\s+me)\s+(the\s+direct|the\s+exact)\s+(answers|solutions)\s+(for\s+my\s+test|for\s+exam)\b", re.IGNORECASE),
    ]

    # Content safety triggers
    HARMFUL_PATTERNS = [
        re.compile(r"\b(how\s+to\s+(make|build)\s+(a\s+bomb|explosive|weapon))\b", re.IGNORECASE),
        re.compile(r"\b(how\s+to\s+(commit\s+suicide|kill\s+myself|self\s*harm))\b", re.IGNORECASE),
    ]

    def evaluate_input(
        self,
        text: str,
        grade_band: GradeBand = GradeBand.HIGH,
    ) -> SafetyDecision:
        """Evaluate a student input prompt for safety and integrity."""
        clean = text.strip()

        # Check critical harm / self-harm
        for pat in self.HARMFUL_PATTERNS:
            if pat.search(clean):
                logger.warning("Safety policy violation: harmful content detected in input.")
                return SafetyDecision(
                    allowed=False,
                    reason="Harmful or dangerous content query rejected.",
                    socratic_redirection=(
                        "I cannot assist with dangerous or harmful activities. If you are experiencing distress, "
                        "please reach out to a trusted adult or crisis support."
                    ),
                )

        # Check academic integrity / cheating
        for pat in self.CHEATING_PATTERNS:
            if pat.search(clean):
                logger.info("Academic integrity boundary triggered: redirected to Socratic guidance.")
                return SafetyDecision(
                    allowed=False,
                    is_cheating_attempt=True,
                    reason="Direct test or assignment completion request.",
                    socratic_redirection=(
                        "I cannot complete your exam, test, or assignment for you. I can, however, "
                        "help you understand the principles and practice similar problems step-by-step. "
                        "What concept is puzzling you?"
                    ),
                )

        return SafetyDecision(allowed=True)

    def evaluate_output(
        self,
        text: str,
        grade_band: GradeBand = GradeBand.HIGH,
    ) -> SafetyDecision:
        """Verify assistant output conforms to safety requirements."""
        clean = text.strip()
        for pat in self.HARMFUL_PATTERNS:
            if pat.search(clean):
                logger.error("Safety policy violation: model attempted to generate harmful content.")
                return SafetyDecision(
                    allowed=False,
                    reason="Harmful content generated by model.",
                    socratic_redirection="I apologize, but I cannot provide that information.",
                )

        return SafetyDecision(allowed=True)
